apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreact-deployment
  labels:
    app: myreact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myreact
  template:
    metadata:
      labels:
        app: myreact
    spec:
      containers:
      - name: myreact-container
        image: scott2srikanth/myreact:latest
        ports:
        - containerPort: 3000
        
---

apiVersion: v1
kind: Service
metadata:
  name: myreact-service
spec:
  type: LoadBalancer
  selector:
    app: myreact
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000